const rsiStrategy = require("./RsiStrategy");
const macdStrategy = require("./MacdStrategy");
const breakoutStrategy = require("./BreakoutStrategy");
const db = require("./DatabaseService");
const eventBus = require("./EventBus");
const logger = require("./LoggerService");
const marketCondition = require("./MarketConditionService");
const aiLearning = require("./AIZtronLearningService");

const SYMBOLS = ["BTCUSDT", "ETHUSDT", "BNBUSDT"];

// 🔥 AJUSTADO: Pesos para confiança (menos conservador)
const CONFIDENCE_WEIGHTS = {
  RSI: 0.30,      // +5%
  MACD: 0.30,     // +5%
  BREAKOUT: 0.20, // mesmo
  VOLUME: 0.10,   // -5%
  SENTIMENT: 0.10 // -5%
};

class SignalService {
  constructor() {
    this.activeSignals = [];
    this.running = false;
    this._intervalId = null;
    this.signalHistory = [];
    logger.info("SignalService initialized", { service: "SignalService" });
  }

  start() {
    if (this.running) return;
    this.running = true;
    // 🔥 AUMENTADO: scan a cada 10 segundos (antes 15)
    this._intervalId = setInterval(() => this._scan(), 10000);
    logger.info("SignalService started", { service: "SignalService" });
  }

  stop() {
    this.running = false;
    if (this._intervalId) { 
      clearInterval(this._intervalId); 
      this._intervalId = null; 
    }
    logger.info("SignalService stopped", { service: "SignalService" });
  }

  _normalizeString(str, type = "status") {
    if (!str) return type === "status" ? "ACTIVE" : "UNKNOWN";
    const upper = str.toUpperCase();
    if (type === "status") {
      if (upper === "ATIVA" || upper === "ATIVO" || upper === "ACTIVE") return "ACTIVE";
      if (upper === "FECHADA" || upper === "CLOSED") return "CLOSED";
      return "ACTIVE";
    }
    if (type === "type") {
      if (upper === "COMPRA" || upper === "BUY") return "BUY";
      if (upper === "VENDA" || upper === "SELL") return "SELL";
      return upper;
    }
    return str;
  }

  _normalizeSignal(signal) {
    return {
      id: signal.id,
      symbol: signal.symbol || signal.símbolo,
      type: this._normalizeString(signal.type || signal.tipo, "type"),
      price: signal.price || signal.preço || null,
      confidence: signal.confidence || signal.confiança || 70,
      strategy: signal.strategy || signal.estratégia || "UNKNOWN",
      reason: signal.reason || signal.motivo || "Signal generated by AZTRON AI",
      timestamp: signal.timestamp,
      status: this._normalizeString(signal.status, "status"),
      positionSizeMultiplier: signal.positionSizeMultiplier || signal.multiplicadorTamanhoDaPosição || 1,
      consensusCount: signal.consensusCount || signal.contagemDeConsenso || 1
    };
  }

  _isMarketConditionValid(symbol) {
    try {
      const condition = marketCondition.getCondition(symbol);
      
      // 🔥 REMOVIDO: bloqueio de mercado ranging (agora permite)
      // if (condition && condition.regime === "ranging") {
      //   logger.debug(`Market sideways for ${symbol}, skipping signals`);
      //   return false;
      // }
      
      // 🔥 REDUZIDO: volatilidade mínima de 0.1% (antes 0.3%)
      if (condition && condition.volatility < 0.1) {
        logger.debug(`Low volatility (${condition.volatility}%) for ${symbol}, skipping`, { service: "SignalService" });
        return false;
      }
      
      return true;
    } catch (error) {
      return true;
    }
  }

  _calculateRealConfidence(result, symbol) {
    let baseConfidence = result.confidence || 60;
    let adjustments = [];
    
    try {
      const condition = marketCondition.getCondition(symbol);
      if (condition) {
        // 🔥 AUMENTADO: bônus para mercado trending (+12% antes +8%)
        if (condition.regime === "trending") {
          baseConfidence += 12;
          adjustments.push("+12% (trending market)");
        } else if (condition.regime === "ranging") {
          // 🔥 REDUZIDO: penalidade para ranging (-8% antes -15%)
          baseConfidence -= 8;
          adjustments.push("-8% (sideways market)");
        }
        
        // 🔥 AUMENTADO: bônus de alinhamento com tendência (+15% antes +10%)
        if (result.signal === "BUY" && condition.trend === "bullish") {
          baseConfidence += 15;
          adjustments.push("+15% (trend aligned)");
        } else if (result.signal === "SELL" && condition.trend === "bearish") {
          baseConfidence += 15;
          adjustments.push("+15% (trend aligned)");
        } else if (result.signal === "BUY" && condition.trend === "bearish") {
          baseConfidence -= 5;  // 🔥 REDUZIDO: penalidade menor (-5% antes -10%)
          adjustments.push("-5% (counter-trend)");
        } else if (result.signal === "SELL" && condition.trend === "bullish") {
          baseConfidence -= 5;
          adjustments.push("-5% (counter-trend)");
        }
      }
      
      try {
        const sentimentService = require("./SentimentService");
        const sentiment = sentimentService.getSentiment();
        
        // 🔥 AJUSTADO: limites mais agressivos
        if (result.signal === "BUY" && sentiment.fearGreedIndex < 35) {  // antes 30
          baseConfidence += 15;  // antes 12
          adjustments.push("+15% (fear = buy opportunity)");
        } else if (result.signal === "BUY" && sentiment.fearGreedIndex > 75) { // antes 70
          baseConfidence -= 10; // antes -15
          adjustments.push("-10% (extreme greed = cautious)");
        } else if (result.signal === "SELL" && sentiment.fearGreedIndex > 65) { // antes 70
          baseConfidence += 12; // antes 10
          adjustments.push("+12% (greed = sell opportunity)");
        } else if (result.signal === "SELL" && sentiment.fearGreedIndex < 35) { // antes 30
          baseConfidence -= 8; // antes -10
          adjustments.push("-8% (fear = avoid selling)");
        }
      } catch (e) {}
      
      try {
        const prediction = aiLearning.predictSignal({
          symbol: symbol,
          strategy: result.strategy,
          signal: result.signal,
          confidence: baseConfidence
        });
        
        if (prediction && prediction.recommendation === "FOLLOW") {
          baseConfidence += 8; // antes 5
          adjustments.push(`+8% (AI pattern match: ${prediction.patternUsed})`);
        } else if (prediction && prediction.recommendation === "SKIP") {
          baseConfidence -= 5; // antes -10
          adjustments.push("-5% (AI recommends skip)");
        }
      } catch (e) {}
      
    } catch (error) {
      logger.warn(`Confidence calculation error: ${error.message}`, { service: "SignalService" });
    }
    
    // 🔥 AJUSTADO: limites mais amplos (30-98% antes 35-95%)
    const finalConfidence = Math.min(98, Math.max(30, Math.round(baseConfidence)));
    
    if (adjustments.length > 0) {
      logger.debug(`Confidence for ${symbol}: ${result.confidence}% → ${finalConfidence}% (${adjustments.join(", ")})`, {
        service: "SignalService"
      });
    }
    
    return finalConfidence;
  }

  _checkConsensus(symbol) {
    try {
      const strategies = [rsiStrategy, macdStrategy, breakoutStrategy];
      const results = [];
      
      for (const strategy of strategies) {
        const result = strategy.analyze(symbol);
        // 🔥 REDUZIDO: confiança mínima para considerar (40% antes 50%)
        if (result && result.confidence > 40) {
          results.push({
            signal: result.signal,
            confidence: result.confidence,
            strategy: result.strategy
          });
        }
      }
      
      if (results.length === 0) return null;
      
      const allBuy = results.every(r => r.signal === "BUY");
      const allSell = results.every(r => r.signal === "SELL");
      
      if (allBuy || allSell) {
        const avgConfidence = results.reduce((sum, r) => sum + r.confidence, 0) / results.length;
        const strategiesList = results.map(r => r.strategy).join(", ");
        
        return {
          consensus: true,
          signal: allBuy ? "BUY" : "SELL",
          // 🔥 AUMENTADO: bônus de consenso +15% (antes +10%)
          confidence: Math.min(95, Math.round(avgConfidence + 15)),
          strategies: strategiesList,
          count: results.length
        };
      }
      
      return {
        consensus: false,
        signals: results
      };
      
    } catch (error) {
      return null;
    }
  }

  _getPositionSizeMultiplier(confidence) {
    // 🔥 AJUSTADO: multiplicadores maiores
    if (confidence >= 85) return 1.5;   // antes 1.2
    if (confidence >= 75) return 1.2;   // antes 1.0
    if (confidence >= 60) return 0.9;   // antes 0.7
    if (confidence >= 50) return 0.7;   // NOVO: para sinais mais fracos
    return 0.5;                          // antes 0.0
  }

  _scan() {
    const strategies = [rsiStrategy, macdStrategy, breakoutStrategy];
    
    for (const sym of SYMBOLS) {
      if (!this._isMarketConditionValid(sym)) continue;
      
      const consensus = this._checkConsensus(sym);
      
      // 🔥 REDUZIDO: confiança mínima para consenso (65% antes 70%)
      if (consensus && consensus.consensus && consensus.confidence > 65) {
        const finalConfidence = this._calculateRealConfidence(
          { signal: consensus.signal, confidence: consensus.confidence, strategy: "CONSENSUS" },
          sym
        );
        
        const positionMultiplier = this._getPositionSizeMultiplier(finalConfidence);
        
        const signal = {
          id: `sig_${Date.now()}_${Math.random().toString(36).slice(2)}`,
          symbol: sym,
          type: consensus.signal === "BUY" ? "BUY" : "SELL",
          price: null,
          confidence: finalConfidence,
          strategy: `CONSENSUS_${consensus.strategies}`,
          reason: `Consensus signal from ${consensus.count} strategies: ${consensus.strategies}`,
          timestamp: new Date().toISOString(),
          status: "ACTIVE",
          positionSizeMultiplier: positionMultiplier,
          consensusCount: consensus.count
        };
        
        this._emitSignal(signal);
        continue;
      }
      
      for (const strategy of strategies) {
        try {
          const result = strategy.analyze(sym);
          
          // 🔥 REDUZIDO: confiança mínima para sinal individual (55% antes 65%)
          if (result && result.confidence > 55) {
            const finalConfidence = this._calculateRealConfidence(result, sym);
            
            // 🔥 REDUZIDO: confiança mínima final (55% antes 60%)
            if (finalConfidence < 55) {
              logger.debug(`Signal ${result.signal} ${sym} rejected: final confidence ${finalConfidence}% < 55%`, {
                service: "SignalService"
              });
              continue;
            }
            
            const positionMultiplier = this._getPositionSizeMultiplier(finalConfidence);
            
            const signal = {
              id: `sig_${Date.now()}_${Math.random().toString(36).slice(2)}`,
              symbol: result.symbol,
              type: result.signal === "BUY" ? "BUY" : "SELL",
              price: Math.round(result.price * 100) / 100,
              confidence: finalConfidence,
              strategy: result.strategy,
              reason: result.reason || "Signal generated by AZTRON AI",
              timestamp: new Date().toISOString(),
              status: "ACTIVE",
              positionSizeMultiplier: positionMultiplier,
              originalConfidence: result.confidence,
              adjustments: finalConfidence - result.confidence
            };
            
            this._emitSignal(signal);
          }
        } catch (err) {
          logger.error(`Signal scan error for ${sym}: ${err.message}`, { service: "SignalService" });
        }
      }
    }
    
    this.activeSignals = this.activeSignals.filter(s => 
      Date.now() - new Date(s.timestamp).getTime() < 2 * 60 * 60 * 1000
    );
  }

  _emitSignal(signal) {
    const normalizedSignal = this._normalizeSignal(signal);
    
    this.activeSignals.unshift(normalizedSignal);
    if (this.activeSignals.length > 50) this.activeSignals.length = 50;
    
    try {
      db.addSignal(normalizedSignal);
    } catch (e) {}
    
    eventBus.emit("signal", normalizedSignal);
    
    const sizeInfo = normalizedSignal.positionSizeMultiplier !== 1.0 
      ? ` (size: ${normalizedSignal.positionSizeMultiplier}x)` 
      : "";
    
    logger.info(`Signal: ${normalizedSignal.type} ${normalizedSignal.symbol} (${normalizedSignal.confidence}% conf)${sizeInfo}`, { 
      service: "SignalService",
      strategy: normalizedSignal.strategy,
      consensusCount: normalizedSignal.consensusCount
    });
  }

  recordSignalOutcome(signalId, wasSuccessful, actualPnl) {
    const signal = this.activeSignals.find(s => s.id === signalId);
    if (signal) {
      signal.outcome = wasSuccessful ? "WIN" : "LOSS";
      signal.actualPnl = actualPnl;
      signal.closedAt = new Date().toISOString();
      
      try {
        aiLearning.learnFromTrade({
          id: signalId,
          symbol: signal.symbol,
          action: signal.type,
          pnl: actualPnl,
          pnlPercent: (actualPnl / (signal.price || 1)) * 100,
          wasWin: wasSuccessful,
          strategy: signal.strategy,
          status: "CLOSED",
          conditions: {
            confidence: signal.confidence,
            sentiment: signal.sentiment
          }
        });
      } catch (e) {}
    }
  }

  getSignals(limit = 20) { 
    return this.activeSignals.slice(0, limit); 
  }
  
  getLatest() { 
    return this.activeSignals[0] || null; 
  }
  
  getStats() {
    const total = this.activeSignals.length;
    const buys = this.activeSignals.filter(s => s.type === "BUY").length;
    const sells = this.activeSignals.filter(s => s.type === "SELL").length;
    const avgConfidence = total > 0 
      ? Math.round(this.activeSignals.reduce((sum, s) => sum + s.confidence, 0) / total)
      : 0;
    
    return {
      activeSignals: total,
      buySignals: buys,
      sellSignals: sells,
      averageConfidence: avgConfidence,
      highConfidenceSignals: this.activeSignals.filter(s => s.confidence >= 80).length
    };
  }
}

module.exports = new SignalService();
